app:
  name: DisembodiedSpecter
  port: 8080
  version: 0.0.1

database:
  host: localhost
  port: 5432
  username: postgres
  password: yuanshen123
  dbname: disembodied_specter

jwt:
  secret: 123456
  expire: 1800
  refresh_expire: 604800

redis:
  init_addr: localhost:6379
  password: "yuanshen123"
  db: 1
  pool_size: 100
  conn_with_timeout: 5s

cache:
  base_key: "private:cache"
  expire: 604800

security:
  white_list:
    - "/api/v1/*"
    - "/swagger/*"
    - "/api/ws/*"
  security_handler: "Authorization"
  security_header_prefix: "Bearer "

sync:
  enabled: true
  player_data_interval: 300
