// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"DisembodiedSpecter/internal/config"
	"DisembodiedSpecter/internal/filter"
	"DisembodiedSpecter/internal/handlers"
	"DisembodiedSpecter/internal/repository"
	"DisembodiedSpecter/internal/service"
	"DisembodiedSpecter/internal/service/fight/character"
	"DisembodiedSpecter/internal/service/fight/enemy"
	"DisembodiedSpecter/internal/service/global"
	"DisembodiedSpecter/internal/utils"
	"github.com/redis/rueidis"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, redisClient rueidis.Client) (*Init, func(), error) {
	db, cleanup, err := repository.ProvideDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	playerRepo := repository.NewGormPlayerRepo(db)
	playerDataManager := utils.NewPlayerDataManager(redisClient, playerRepo)
	gameRepo := repository.NewGormGameRepo(db)
	gameContentManager := utils.NewGameContentManager(redisClient, gameRepo)
	syncScheduler := utils.NewSyncScheduler(cfg, playerDataManager, gameContentManager)
	userRepo := repository.NewUserRepo(db)
	tokenManager := utils.NewTokenManager(redisClient, cfg)
	emailRepo := repository.NewEmailRepo(db)
	mailManager := utils.NewMailManager(emailRepo, redisClient)
	codeManager := utils.NewCodeManager(redisClient, mailManager)
	authUseCase := service.NewAuthUseCase(userRepo, tokenManager, codeManager)
	authHandler := handlers.NewAuthHandler(authUseCase)
	cacheManager := utils.NewCacheManager(redisClient, cfg)
	userUseCase := service.NewUserUseCase(redisClient, cacheManager, playerDataManager)
	userHandler := handlers.NewUserHandler(userUseCase)
	adminUseCase := service.NewAdminUseCase(userRepo, playerRepo, emailRepo, playerDataManager, gameRepo, gameContentManager)
	adminHandler := handlers.NewAdminHandler(adminUseCase)
	authFilter := filter.NewAuthFilter(cfg, tokenManager, redisClient)
	skillManager := character.NewSkillManager(gameContentManager)
	enemyManager := enemy.NewEnemyManager(gameContentManager)
	fightUseCase := service.NewFightUseCase(redisClient, cfg, gameContentManager, playerDataManager, skillManager, enemyManager)
	globalEngine := global.NewGlobalEngine(redisClient, playerDataManager)
	globalUseCase := service.NewGlobalUseCase(gameContentManager, playerDataManager, globalEngine, redisClient, cfg)
	webSocketHandler := handlers.NewWebSocketHandler(fightUseCase, globalUseCase)
	engine := handlers.NewRouter(authHandler, userHandler, adminHandler, authFilter, webSocketHandler)
	init := NewInit(syncScheduler, engine)
	return init, func() {
		cleanup()
	}, nil
}
