// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0--rc2
// source: fight_message.proto

package pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Switch_Phase_Option int32

const (
	Switch_Phase_Option_START_PHASE       Switch_Phase_Option = 0 // 开始本轮回合战斗
	Switch_Phase_Option_EXIT_FIGHT        Switch_Phase_Option = 1 // 退出战斗
	Switch_Phase_Option_RETURN_PREV_PHASE Switch_Phase_Option = 2 // 回到上一回合
)

// Enum value maps for Switch_Phase_Option.
var (
	Switch_Phase_Option_name = map[int32]string{
		0: "START_PHASE",
		1: "EXIT_FIGHT",
		2: "RETURN_PREV_PHASE",
	}
	Switch_Phase_Option_value = map[string]int32{
		"START_PHASE":       0,
		"EXIT_FIGHT":        1,
		"RETURN_PREV_PHASE": 2,
	}
)

func (x Switch_Phase_Option) Enum() *Switch_Phase_Option {
	p := new(Switch_Phase_Option)
	*p = x
	return p
}

func (x Switch_Phase_Option) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Switch_Phase_Option) Descriptor() protoreflect.EnumDescriptor {
	return file_fight_message_proto_enumTypes[0].Descriptor()
}

func (Switch_Phase_Option) Type() protoreflect.EnumType {
	return &file_fight_message_proto_enumTypes[0]
}

func (x Switch_Phase_Option) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Switch_Phase_Option.Descriptor instead.
func (Switch_Phase_Option) EnumDescriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{0}
}

// 战斗日志类型。
//
// 服务端执行战斗时按发生顺序记录，客户端按同一顺序回放演出（动画/飘字/血条）。
// 约定：日志是"一次性事件"，状态（FightStatus）是"当前快照"，两者互不替代。
//
// 每一类事件都有**独立的详情 message**（见下方 AttackLog/RecoverLog/...），
// 由 FightLog.detail 这个 oneof 承载；type 与 detail 的分支必须一一对应（服务端保证）。
//
// 注意：**没有"出手/CAST"类型** —— 出手动作由攻击事件自身承载
// （source 就是出手方），因此被动追加攻击天然也会播出手动画。
// 回合推进、阶段切换不下发日志（客户端从 FightStatus.round / state_number 取）。
type FightLogType int32

const (
	FightLogType_LOG_UNKNOWN FightLogType = 0
	FightLogType_LOG_ATTACK  FightLogType = 1 // 攻击（含被被动/特殊受击接管的情况）
	FightLogType_LOG_RECOVER FightLogType = 2 // 恢复
	FightLogType_LOG_COUNTER FightLogType = 3 // 计数器变化（含 buff 层数/时间变化）
	FightLogType_LOG_BUFF    FightLogType = 4 // 获得/刷新 buff
	FightLogType_LOG_DEATH   FightLogType = 5 // 阵亡
	FightLogType_LOG_OTHER   FightLogType = 6 // 其他（详情走 JSON）
)

// Enum value maps for FightLogType.
var (
	FightLogType_name = map[int32]string{
		0: "LOG_UNKNOWN",
		1: "LOG_ATTACK",
		2: "LOG_RECOVER",
		3: "LOG_COUNTER",
		4: "LOG_BUFF",
		5: "LOG_DEATH",
		6: "LOG_OTHER",
	}
	FightLogType_value = map[string]int32{
		"LOG_UNKNOWN": 0,
		"LOG_ATTACK":  1,
		"LOG_RECOVER": 2,
		"LOG_COUNTER": 3,
		"LOG_BUFF":    4,
		"LOG_DEATH":   5,
		"LOG_OTHER":   6,
	}
)

func (x FightLogType) Enum() *FightLogType {
	p := new(FightLogType)
	*p = x
	return p
}

func (x FightLogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FightLogType) Descriptor() protoreflect.EnumDescriptor {
	return file_fight_message_proto_enumTypes[1].Descriptor()
}

func (FightLogType) Type() protoreflect.EnumType {
	return &file_fight_message_proto_enumTypes[1]
}

func (x FightLogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FightLogType.Descriptor instead.
func (FightLogType) EnumDescriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{1}
}

type Buff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuffId        int32                  `protobuf:"varint,1,opt,name=buff_id,json=buffId,proto3" json:"buff_id,omitempty"` // buffID
	Time          int32                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`                   // buff持续时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buff) Reset() {
	*x = Buff{}
	mi := &file_fight_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buff) ProtoMessage() {}

func (x *Buff) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buff.ProtoReflect.Descriptor instead.
func (*Buff) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{0}
}

func (x *Buff) GetBuffId() int32 {
	if x != nil {
		return x.BuffId
	}
	return 0
}

func (x *Buff) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 角色状态
type CharacterStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        int32                  `protobuf:"varint,1,opt,name=health,proto3" json:"health,omitempty"`                                      // 生命值
	Attack        float64                `protobuf:"fixed64,2,opt,name=attack,proto3" json:"attack,omitempty"`                                     // 攻击倍率
	Defense       int32                  `protobuf:"varint,3,opt,name=defense,proto3" json:"defense,omitempty"`                                    // 防御值
	Buffs         []*Buff                `protobuf:"bytes,4,rep,name=buffs,proto3" json:"buffs,omitempty"`                                         // buff列表
	IsMyCharacter bool                   `protobuf:"varint,5,opt,name=is_my_character,json=isMyCharacter,proto3" json:"is_my_character,omitempty"` // 是否是我的角色
	CharacterId   int32                  `protobuf:"varint,6,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`         // 角色/敌人的 DB ID（前端据此选择立绘与动画资源）
	MaxHealth     int32                  `protobuf:"varint,7,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`               // 生命上限（血条基准）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterStatus) Reset() {
	*x = CharacterStatus{}
	mi := &file_fight_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStatus) ProtoMessage() {}

func (x *CharacterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStatus.ProtoReflect.Descriptor instead.
func (*CharacterStatus) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterStatus) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *CharacterStatus) GetAttack() float64 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *CharacterStatus) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *CharacterStatus) GetBuffs() []*Buff {
	if x != nil {
		return x.Buffs
	}
	return nil
}

func (x *CharacterStatus) GetIsMyCharacter() bool {
	if x != nil {
		return x.IsMyCharacter
	}
	return false
}

func (x *CharacterStatus) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterStatus) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

// 道具
type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        int32                  `protobuf:"varint,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"` // 道具ID
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 道具数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_fight_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{2}
}

func (x *Tool) GetToolId() int32 {
	if x != nil {
		return x.ToolId
	}
	return 0
}

func (x *Tool) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 技能
type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int32                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`             // 技能ID
	TargetId      int32                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`          // 目标ID
	CharacterId   int32                  `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // 角色ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_fight_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{3}
}

func (x *Skill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *Skill) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Skill) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

// 位置
type Site struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IsMainActionCharacter bool                   `protobuf:"varint,1,opt,name=is_main_action_character,json=isMainActionCharacter,proto3" json:"is_main_action_character,omitempty"` // 是否是行动角色
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_fight_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{4}
}

func (x *Site) GetIsMainActionCharacter() bool {
	if x != nil {
		return x.IsMainActionCharacter
	}
	return false
}

// 战斗状态
type FightStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsSelfRound    bool                   `protobuf:"varint,1,opt,name=is_self_round,json=isSelfRound,proto3" json:"is_self_round,omitempty"`                                                 // 是否是我的回合
	Round          int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                                                                                  // 回合数
	Characters     []*CharacterStatus     `protobuf:"bytes,3,rep,name=characters,proto3" json:"characters,omitempty"`                                                                         // 角色状态
	Sites          []*Site                `protobuf:"bytes,4,rep,name=sites,proto3" json:"sites,omitempty"`                                                                                   // 位置
	Tools          []*Tool                `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`                                                                                   // 道具列表
	NowFightStatus int32                  `protobuf:"varint,6,opt,name=now_fight_status,json=nowFightStatus,proto3" json:"now_fight_status,omitempty"`                                        // 当前战斗状态
	Counters       map[string]float32     `protobuf:"bytes,7,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // 计数器
	StateNumber    int32                  `protobuf:"varint,8,opt,name=state_number,json=stateNumber,proto3" json:"state_number,omitempty"`                                                   // 状态编号
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FightStatus) Reset() {
	*x = FightStatus{}
	mi := &file_fight_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FightStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FightStatus) ProtoMessage() {}

func (x *FightStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FightStatus.ProtoReflect.Descriptor instead.
func (*FightStatus) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{5}
}

func (x *FightStatus) GetIsSelfRound() bool {
	if x != nil {
		return x.IsSelfRound
	}
	return false
}

func (x *FightStatus) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *FightStatus) GetCharacters() []*CharacterStatus {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *FightStatus) GetSites() []*Site {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *FightStatus) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *FightStatus) GetNowFightStatus() int32 {
	if x != nil {
		return x.NowFightStatus
	}
	return 0
}

func (x *FightStatus) GetCounters() map[string]float32 {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *FightStatus) GetStateNumber() int32 {
	if x != nil {
		return x.StateNumber
	}
	return 0
}

// 选择技能
type C2S_ChoseSkills struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"` // 技能列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_ChoseSkills) Reset() {
	*x = C2S_ChoseSkills{}
	mi := &file_fight_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_ChoseSkills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ChoseSkills) ProtoMessage() {}

func (x *C2S_ChoseSkills) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ChoseSkills.ProtoReflect.Descriptor instead.
func (*C2S_ChoseSkills) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_ChoseSkills) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

// 使用道具
type C2S_UseTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        int32                  `protobuf:"varint,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`       // 道具ID
	TargetId      int32                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_UseTool) Reset() {
	*x = C2S_UseTool{}
	mi := &file_fight_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_UseTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_UseTool) ProtoMessage() {}

func (x *C2S_UseTool) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_UseTool.ProtoReflect.Descriptor instead.
func (*C2S_UseTool) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{7}
}

func (x *C2S_UseTool) GetToolId() int32 {
	if x != nil {
		return x.ToolId
	}
	return 0
}

func (x *C2S_UseTool) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 阶段切换
type C2S_SwitchPhase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         Switch_Phase_Option    `protobuf:"varint,1,opt,name=phase,proto3,enum=proto.Switch_Phase_Option" json:"phase,omitempty"` // 阶段选项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_SwitchPhase) Reset() {
	*x = C2S_SwitchPhase{}
	mi := &file_fight_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_SwitchPhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SwitchPhase) ProtoMessage() {}

func (x *C2S_SwitchPhase) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SwitchPhase.ProtoReflect.Descriptor instead.
func (*C2S_SwitchPhase) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{8}
}

func (x *C2S_SwitchPhase) GetPhase() Switch_Phase_Option {
	if x != nil {
		return x.Phase
	}
	return Switch_Phase_Option_START_PHASE
}

// 同步战斗状态请求
type Msg_SyncFightStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *FightStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`        // 战斗状态
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 消息发送时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg_SyncFightStatus) Reset() {
	*x = Msg_SyncFightStatus{}
	mi := &file_fight_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg_SyncFightStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg_SyncFightStatus) ProtoMessage() {}

func (x *Msg_SyncFightStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg_SyncFightStatus.ProtoReflect.Descriptor instead.
func (*Msg_SyncFightStatus) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{9}
}

func (x *Msg_SyncFightStatus) GetStatus() *FightStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Msg_SyncFightStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 攻击事件详情
type AttackLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        int32                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`                     // 来源战斗位索引（出手方）
	Target        int32                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`                     // 目标战斗位索引（受击方）
	Damage        int32                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`                     // **最终伤害**：实际掉血量；被被动/特殊受击抵消掉的部分不计入
	HpBefore      int32                  `protobuf:"varint,4,opt,name=hp_before,json=hpBefore,proto3" json:"hp_before,omitempty"` // 结算前生命值
	HpAfter       int32                  `protobuf:"varint,5,opt,name=hp_after,json=hpAfter,proto3" json:"hp_after,omitempty"`    // 结算后生命值
	Ref           int32                  `protobuf:"varint,6,opt,name=ref,proto3" json:"ref,omitempty"`                           // 伤害来源：>0 技能ID；<0 −buffID；0 被动
	Special       int32                  `protobuf:"varint,7,opt,name=special,proto3" json:"special,omitempty"`                   // 本次攻击触发的被动/特殊受击效果：>0 角色DB ID；<0 −buffID；0 无
	Other         string                 `protobuf:"bytes,8,opt,name=other,proto3" json:"other,omitempty"`                        // 攻击事件原始 other（JSON 原文，服务端不解析、原样透传）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackLog) Reset() {
	*x = AttackLog{}
	mi := &file_fight_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackLog) ProtoMessage() {}

func (x *AttackLog) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackLog.ProtoReflect.Descriptor instead.
func (*AttackLog) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{10}
}

func (x *AttackLog) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *AttackLog) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *AttackLog) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *AttackLog) GetHpBefore() int32 {
	if x != nil {
		return x.HpBefore
	}
	return 0
}

func (x *AttackLog) GetHpAfter() int32 {
	if x != nil {
		return x.HpAfter
	}
	return 0
}

func (x *AttackLog) GetRef() int32 {
	if x != nil {
		return x.Ref
	}
	return 0
}

func (x *AttackLog) GetSpecial() int32 {
	if x != nil {
		return x.Special
	}
	return 0
}

func (x *AttackLog) GetOther() string {
	if x != nil {
		return x.Other
	}
	return ""
}

// 恢复事件详情（与攻击同构）
type RecoverLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        int32                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`                     // 来源战斗位索引
	Target        int32                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`                     // 目标战斗位索引
	Recover       int32                  `protobuf:"varint,3,opt,name=recover,proto3" json:"recover,omitempty"`                   // **实际恢复量**（血量差）
	HpBefore      int32                  `protobuf:"varint,4,opt,name=hp_before,json=hpBefore,proto3" json:"hp_before,omitempty"` // 结算前生命值
	HpAfter       int32                  `protobuf:"varint,5,opt,name=hp_after,json=hpAfter,proto3" json:"hp_after,omitempty"`    // 结算后生命值
	Ref           int32                  `protobuf:"varint,6,opt,name=ref,proto3" json:"ref,omitempty"`                           // 恢复来源：>0 技能ID；<0 −buffID；0 被动
	Special       int32                  `protobuf:"varint,7,opt,name=special,proto3" json:"special,omitempty"`                   // 本次恢复触发的被动/特殊效果：>0 角色DB ID；<0 −buffID；0 无
	Other         string                 `protobuf:"bytes,8,opt,name=other,proto3" json:"other,omitempty"`                        // 恢复事件原始 other（JSON 原文）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverLog) Reset() {
	*x = RecoverLog{}
	mi := &file_fight_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverLog) ProtoMessage() {}

func (x *RecoverLog) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverLog.ProtoReflect.Descriptor instead.
func (*RecoverLog) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{11}
}

func (x *RecoverLog) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RecoverLog) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *RecoverLog) GetRecover() int32 {
	if x != nil {
		return x.Recover
	}
	return 0
}

func (x *RecoverLog) GetHpBefore() int32 {
	if x != nil {
		return x.HpBefore
	}
	return 0
}

func (x *RecoverLog) GetHpAfter() int32 {
	if x != nil {
		return x.HpAfter
	}
	return 0
}

func (x *RecoverLog) GetRef() int32 {
	if x != nil {
		return x.Ref
	}
	return 0
}

func (x *RecoverLog) GetSpecial() int32 {
	if x != nil {
		return x.Special
	}
	return 0
}

func (x *RecoverLog) GetOther() string {
	if x != nil {
		return x.Other
	}
	return ""
}

// 计数器变化事件详情。
//
// 战斗内一切"计数"都走这里，包括 buff 的层数/时间变化：
// buff 用约定键 "buff:<buffID>:<战斗位索引>"，值即剩余层数/时间，
// 归零即表示该 buff 失效（客户端据此移除图标），因此不另设"buff 消失"事件。
type CounterLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`      // 计数器键
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"` // 变化值（正=增加，负=减少）
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"` // 变化后的值
	Ref           int32                  `protobuf:"varint,4,opt,name=ref,proto3" json:"ref,omitempty"`     // 触发来源：>0 技能ID；<0 −buffID；0 被动
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterLog) Reset() {
	*x = CounterLog{}
	mi := &file_fight_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterLog) ProtoMessage() {}

func (x *CounterLog) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterLog.ProtoReflect.Descriptor instead.
func (*CounterLog) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{12}
}

func (x *CounterLog) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CounterLog) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *CounterLog) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CounterLog) GetRef() int32 {
	if x != nil {
		return x.Ref
	}
	return 0
}

// 获得/刷新 buff 事件详情。之后的层数/时间变化走 CounterLog。
type BuffLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        int32                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`               // 施加者战斗位索引（-1 表示无来源）
	Target        int32                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`               // 获得者战斗位索引
	BuffId        int32                  `protobuf:"varint,3,opt,name=buff_id,json=buffId,proto3" json:"buff_id,omitempty"` // 获得的 buff ID
	Time          int32                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`                   // 本次时长/层数（已应用默认时长兜底）
	Ref           int32                  `protobuf:"varint,5,opt,name=ref,proto3" json:"ref,omitempty"`                     // 施加来源：>0 技能ID；<0 −buffID；0 被动
	Special       int32                  `protobuf:"varint,6,opt,name=special,proto3" json:"special,omitempty"`             // 施加时触发的被动/特殊效果：>0 角色DB ID；<0 −buffID；0 无
	Other         string                 `protobuf:"bytes,7,opt,name=other,proto3" json:"other,omitempty"`                  // buff 事件原始 other（JSON 原文）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffLog) Reset() {
	*x = BuffLog{}
	mi := &file_fight_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffLog) ProtoMessage() {}

func (x *BuffLog) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffLog.ProtoReflect.Descriptor instead.
func (*BuffLog) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{13}
}

func (x *BuffLog) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *BuffLog) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *BuffLog) GetBuffId() int32 {
	if x != nil {
		return x.BuffId
	}
	return 0
}

func (x *BuffLog) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BuffLog) GetRef() int32 {
	if x != nil {
		return x.Ref
	}
	return 0
}

func (x *BuffLog) GetSpecial() int32 {
	if x != nil {
		return x.Special
	}
	return 0
}

func (x *BuffLog) GetOther() string {
	if x != nil {
		return x.Other
	}
	return ""
}

// 阵亡事件详情
type DeathLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        int32                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"` // 击杀者战斗位索引（-1 表示无来源，如 buff/场地伤害）
	Target        int32                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"` // 阵亡的战斗位索引
	Ref           int32                  `protobuf:"varint,3,opt,name=ref,proto3" json:"ref,omitempty"`       // 致死来源：>0 技能ID；<0 −buffID；0 被动
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeathLog) Reset() {
	*x = DeathLog{}
	mi := &file_fight_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathLog) ProtoMessage() {}

func (x *DeathLog) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathLog.ProtoReflect.Descriptor instead.
func (*DeathLog) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{14}
}

func (x *DeathLog) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *DeathLog) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *DeathLog) GetRef() int32 {
	if x != nil {
		return x.Ref
	}
	return 0
}

// 其他事件详情（战斗结束等；内容由客户端按需解析）
type OtherLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"` // JSON 原文，例如 {"op":"end","win":1}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtherLog) Reset() {
	*x = OtherLog{}
	mi := &file_fight_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherLog) ProtoMessage() {}

func (x *OtherLog) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherLog.ProtoReflect.Descriptor instead.
func (*OtherLog) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{15}
}

func (x *OtherLog) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// 一条战斗日志：信封（通用字段）+ 详情（按类型只有一个分支非空）。
type FightLog struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Seq         int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                    // 同一场战斗内自增序号（客户端可据此排序/去重）
	Type        FightLogType           `protobuf:"varint,2,opt,name=type,proto3,enum=proto.FightLogType" json:"type,omitempty"`          // 事件类型（与 detail 分支一一对应）
	Round       int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`                                // 所属回合数
	StateNumber int32                  `protobuf:"varint,4,opt,name=state_number,json=stateNumber,proto3" json:"state_number,omitempty"` // 所属战斗状态编号
	// Types that are valid to be assigned to Detail:
	//
	//	*FightLog_Attack
	//	*FightLog_Recover
	//	*FightLog_Counter
	//	*FightLog_Buff
	//	*FightLog_Death
	//	*FightLog_Other
	Detail        isFightLog_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FightLog) Reset() {
	*x = FightLog{}
	mi := &file_fight_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FightLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FightLog) ProtoMessage() {}

func (x *FightLog) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FightLog.ProtoReflect.Descriptor instead.
func (*FightLog) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{16}
}

func (x *FightLog) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *FightLog) GetType() FightLogType {
	if x != nil {
		return x.Type
	}
	return FightLogType_LOG_UNKNOWN
}

func (x *FightLog) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *FightLog) GetStateNumber() int32 {
	if x != nil {
		return x.StateNumber
	}
	return 0
}

func (x *FightLog) GetDetail() isFightLog_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *FightLog) GetAttack() *AttackLog {
	if x != nil {
		if x, ok := x.Detail.(*FightLog_Attack); ok {
			return x.Attack
		}
	}
	return nil
}

func (x *FightLog) GetRecover() *RecoverLog {
	if x != nil {
		if x, ok := x.Detail.(*FightLog_Recover); ok {
			return x.Recover
		}
	}
	return nil
}

func (x *FightLog) GetCounter() *CounterLog {
	if x != nil {
		if x, ok := x.Detail.(*FightLog_Counter); ok {
			return x.Counter
		}
	}
	return nil
}

func (x *FightLog) GetBuff() *BuffLog {
	if x != nil {
		if x, ok := x.Detail.(*FightLog_Buff); ok {
			return x.Buff
		}
	}
	return nil
}

func (x *FightLog) GetDeath() *DeathLog {
	if x != nil {
		if x, ok := x.Detail.(*FightLog_Death); ok {
			return x.Death
		}
	}
	return nil
}

func (x *FightLog) GetOther() *OtherLog {
	if x != nil {
		if x, ok := x.Detail.(*FightLog_Other); ok {
			return x.Other
		}
	}
	return nil
}

type isFightLog_Detail interface {
	isFightLog_Detail()
}

type FightLog_Attack struct {
	Attack *AttackLog `protobuf:"bytes,5,opt,name=attack,proto3,oneof"` // 攻击
}

type FightLog_Recover struct {
	Recover *RecoverLog `protobuf:"bytes,6,opt,name=recover,proto3,oneof"` // 恢复
}

type FightLog_Counter struct {
	Counter *CounterLog `protobuf:"bytes,7,opt,name=counter,proto3,oneof"` // 计数器变化
}

type FightLog_Buff struct {
	Buff *BuffLog `protobuf:"bytes,8,opt,name=buff,proto3,oneof"` // 获得/刷新 buff
}

type FightLog_Death struct {
	Death *DeathLog `protobuf:"bytes,9,opt,name=death,proto3,oneof"` // 阵亡
}

type FightLog_Other struct {
	Other *OtherLog `protobuf:"bytes,10,opt,name=other,proto3,oneof"` // 其他
}

func (*FightLog_Attack) isFightLog_Detail() {}

func (*FightLog_Recover) isFightLog_Detail() {}

func (*FightLog_Counter) isFightLog_Detail() {}

func (*FightLog_Buff) isFightLog_Detail() {}

func (*FightLog_Death) isFightLog_Detail() {}

func (*FightLog_Other) isFightLog_Detail() {}

// 战斗日志批次（服务端 → 客户端）。
// 服务端在每次下发权威状态**之前**先发本批日志，因此客户端收到的
// "日志流 + 状态快照"天然有序：先按日志演出，播完再落地状态。
type S2C_FightLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*FightLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"` // 按发生顺序排列的日志
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_FightLogs) Reset() {
	*x = S2C_FightLogs{}
	mi := &file_fight_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_FightLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_FightLogs) ProtoMessage() {}

func (x *S2C_FightLogs) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_FightLogs.ProtoReflect.Descriptor instead.
func (*S2C_FightLogs) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{17}
}

func (x *S2C_FightLogs) GetLogs() []*FightLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 顶层消息包装器 (Envelope)
type FightMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SequenceId uint64                 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"` // 消息序号 (用于处理乱序、丢包或消息确认)
	Timestamp  int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // 消息发送时间戳
	// Types that are valid to be assigned to Payload:
	//
	//	*FightMessage_ChoseSkill
	//	*FightMessage_UseTool
	//	*FightMessage_SwitchPhase
	//	*FightMessage_SyncFightStatus
	//	*FightMessage_FightLogs
	Payload       isFightMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FightMessage) Reset() {
	*x = FightMessage{}
	mi := &file_fight_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FightMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FightMessage) ProtoMessage() {}

func (x *FightMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FightMessage.ProtoReflect.Descriptor instead.
func (*FightMessage) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{18}
}

func (x *FightMessage) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *FightMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FightMessage) GetPayload() isFightMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FightMessage) GetChoseSkill() *C2S_ChoseSkills {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_ChoseSkill); ok {
			return x.ChoseSkill
		}
	}
	return nil
}

func (x *FightMessage) GetUseTool() *C2S_UseTool {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_UseTool); ok {
			return x.UseTool
		}
	}
	return nil
}

func (x *FightMessage) GetSwitchPhase() *C2S_SwitchPhase {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_SwitchPhase); ok {
			return x.SwitchPhase
		}
	}
	return nil
}

func (x *FightMessage) GetSyncFightStatus() *Msg_SyncFightStatus {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_SyncFightStatus); ok {
			return x.SyncFightStatus
		}
	}
	return nil
}

func (x *FightMessage) GetFightLogs() *S2C_FightLogs {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_FightLogs); ok {
			return x.FightLogs
		}
	}
	return nil
}

type isFightMessage_Payload interface {
	isFightMessage_Payload()
}

type FightMessage_ChoseSkill struct {
	ChoseSkill *C2S_ChoseSkills `protobuf:"bytes,3,opt,name=chose_skill,json=choseSkill,proto3,oneof"` // 选择技能
}

type FightMessage_UseTool struct {
	UseTool *C2S_UseTool `protobuf:"bytes,4,opt,name=use_tool,json=useTool,proto3,oneof"` // 使用道具
}

type FightMessage_SwitchPhase struct {
	SwitchPhase *C2S_SwitchPhase `protobuf:"bytes,5,opt,name=switch_phase,json=switchPhase,proto3,oneof"` // 阶段切换
}

type FightMessage_SyncFightStatus struct {
	SyncFightStatus *Msg_SyncFightStatus `protobuf:"bytes,6,opt,name=sync_fight_status,json=syncFightStatus,proto3,oneof"` // 同步战斗状态请求
}

type FightMessage_FightLogs struct {
	FightLogs *S2C_FightLogs `protobuf:"bytes,7,opt,name=fight_logs,json=fightLogs,proto3,oneof"` // 战斗日志（服务端 → 客户端）
}

func (*FightMessage_ChoseSkill) isFightMessage_Payload() {}

func (*FightMessage_UseTool) isFightMessage_Payload() {}

func (*FightMessage_SwitchPhase) isFightMessage_Payload() {}

func (*FightMessage_SyncFightStatus) isFightMessage_Payload() {}

func (*FightMessage_FightLogs) isFightMessage_Payload() {}

var File_fight_message_proto protoreflect.FileDescriptor

const file_fight_message_proto_rawDesc = "" +
	"\n" +
	"\x13fight_message.proto\x12\x05proto\"3\n" +
	"\x04Buff\x12\x17\n" +
	"\abuff_id\x18\x01 \x01(\x05R\x06buffId\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x05R\x04time\"\xe8\x01\n" +
	"\x0fCharacterStatus\x12\x16\n" +
	"\x06health\x18\x01 \x01(\x05R\x06health\x12\x16\n" +
	"\x06attack\x18\x02 \x01(\x01R\x06attack\x12\x18\n" +
	"\adefense\x18\x03 \x01(\x05R\adefense\x12!\n" +
	"\x05buffs\x18\x04 \x03(\v2\v.proto.BuffR\x05buffs\x12&\n" +
	"\x0fis_my_character\x18\x05 \x01(\bR\risMyCharacter\x12!\n" +
	"\fcharacter_id\x18\x06 \x01(\x05R\vcharacterId\x12\x1d\n" +
	"\n" +
	"max_health\x18\a \x01(\x05R\tmaxHealth\"5\n" +
	"\x04Tool\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\x05R\x06toolId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"b\n" +
	"\x05Skill\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x05R\askillId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x05R\btargetId\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x05R\vcharacterId\"?\n" +
	"\x04Site\x127\n" +
	"\x18is_main_action_character\x18\x01 \x01(\bR\x15isMainActionCharacter\"\x8d\x03\n" +
	"\vFightStatus\x12\"\n" +
	"\ris_self_round\x18\x01 \x01(\bR\visSelfRound\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x126\n" +
	"\n" +
	"characters\x18\x03 \x03(\v2\x16.proto.CharacterStatusR\n" +
	"characters\x12!\n" +
	"\x05sites\x18\x04 \x03(\v2\v.proto.SiteR\x05sites\x12!\n" +
	"\x05tools\x18\x05 \x03(\v2\v.proto.ToolR\x05tools\x12(\n" +
	"\x10now_fight_status\x18\x06 \x01(\x05R\x0enowFightStatus\x12<\n" +
	"\bcounters\x18\a \x03(\v2 .proto.FightStatus.CountersEntryR\bcounters\x12!\n" +
	"\fstate_number\x18\b \x01(\x05R\vstateNumber\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"7\n" +
	"\x0fC2S_ChoseSkills\x12$\n" +
	"\x06skills\x18\x01 \x03(\v2\f.proto.SkillR\x06skills\"C\n" +
	"\vC2S_UseTool\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\x05R\x06toolId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x05R\btargetId\"C\n" +
	"\x0fC2S_SwitchPhase\x120\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1a.proto.Switch_Phase_OptionR\x05phase\"_\n" +
	"\x13Msg_SyncFightStatus\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.proto.FightStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xcd\x01\n" +
	"\tAttackLog\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x05R\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x05R\x06damage\x12\x1b\n" +
	"\thp_before\x18\x04 \x01(\x05R\bhpBefore\x12\x19\n" +
	"\bhp_after\x18\x05 \x01(\x05R\ahpAfter\x12\x10\n" +
	"\x03ref\x18\x06 \x01(\x05R\x03ref\x12\x18\n" +
	"\aspecial\x18\a \x01(\x05R\aspecial\x12\x14\n" +
	"\x05other\x18\b \x01(\tR\x05other\"\xd0\x01\n" +
	"\n" +
	"RecoverLog\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x05R\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\x12\x18\n" +
	"\arecover\x18\x03 \x01(\x05R\arecover\x12\x1b\n" +
	"\thp_before\x18\x04 \x01(\x05R\bhpBefore\x12\x19\n" +
	"\bhp_after\x18\x05 \x01(\x05R\ahpAfter\x12\x10\n" +
	"\x03ref\x18\x06 \x01(\x05R\x03ref\x12\x18\n" +
	"\aspecial\x18\a \x01(\x05R\aspecial\x12\x14\n" +
	"\x05other\x18\b \x01(\tR\x05other\"\\\n" +
	"\n" +
	"CounterLog\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x10\n" +
	"\x03ref\x18\x04 \x01(\x05R\x03ref\"\xa8\x01\n" +
	"\aBuffLog\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x05R\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\x12\x17\n" +
	"\abuff_id\x18\x03 \x01(\x05R\x06buffId\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x05R\x04time\x12\x10\n" +
	"\x03ref\x18\x05 \x01(\x05R\x03ref\x12\x18\n" +
	"\aspecial\x18\x06 \x01(\x05R\aspecial\x12\x14\n" +
	"\x05other\x18\a \x01(\tR\x05other\"L\n" +
	"\bDeathLog\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x05R\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\x05R\x03ref\"\"\n" +
	"\bOtherLog\x12\x16\n" +
	"\x06detail\x18\x01 \x01(\tR\x06detail\"\x8a\x03\n" +
	"\bFightLog\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.proto.FightLogTypeR\x04type\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12!\n" +
	"\fstate_number\x18\x04 \x01(\x05R\vstateNumber\x12*\n" +
	"\x06attack\x18\x05 \x01(\v2\x10.proto.AttackLogH\x00R\x06attack\x12-\n" +
	"\arecover\x18\x06 \x01(\v2\x11.proto.RecoverLogH\x00R\arecover\x12-\n" +
	"\acounter\x18\a \x01(\v2\x11.proto.CounterLogH\x00R\acounter\x12$\n" +
	"\x04buff\x18\b \x01(\v2\x0e.proto.BuffLogH\x00R\x04buff\x12'\n" +
	"\x05death\x18\t \x01(\v2\x0f.proto.DeathLogH\x00R\x05death\x12'\n" +
	"\x05other\x18\n" +
	" \x01(\v2\x0f.proto.OtherLogH\x00R\x05otherB\b\n" +
	"\x06detail\"4\n" +
	"\rS2C_FightLogs\x12#\n" +
	"\x04logs\x18\x01 \x03(\v2\x0f.proto.FightLogR\x04logs\"\x82\x03\n" +
	"\fFightMessage\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\x04R\n" +
	"sequenceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x129\n" +
	"\vchose_skill\x18\x03 \x01(\v2\x16.proto.C2S_ChoseSkillsH\x00R\n" +
	"choseSkill\x12/\n" +
	"\buse_tool\x18\x04 \x01(\v2\x12.proto.C2S_UseToolH\x00R\auseTool\x12;\n" +
	"\fswitch_phase\x18\x05 \x01(\v2\x16.proto.C2S_SwitchPhaseH\x00R\vswitchPhase\x12H\n" +
	"\x11sync_fight_status\x18\x06 \x01(\v2\x1a.proto.Msg_SyncFightStatusH\x00R\x0fsyncFightStatus\x125\n" +
	"\n" +
	"fight_logs\x18\a \x01(\v2\x14.proto.S2C_FightLogsH\x00R\tfightLogsB\t\n" +
	"\apayload*M\n" +
	"\x13Switch_Phase_Option\x12\x0f\n" +
	"\vSTART_PHASE\x10\x00\x12\x0e\n" +
	"\n" +
	"EXIT_FIGHT\x10\x01\x12\x15\n" +
	"\x11RETURN_PREV_PHASE\x10\x02*}\n" +
	"\fFightLogType\x12\x0f\n" +
	"\vLOG_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"LOG_ATTACK\x10\x01\x12\x0f\n" +
	"\vLOG_RECOVER\x10\x02\x12\x0f\n" +
	"\vLOG_COUNTER\x10\x03\x12\f\n" +
	"\bLOG_BUFF\x10\x04\x12\r\n" +
	"\tLOG_DEATH\x10\x05\x12\r\n" +
	"\tLOG_OTHER\x10\x06B\x06Z\x04./pdb\x06proto3"

var (
	file_fight_message_proto_rawDescOnce sync.Once
	file_fight_message_proto_rawDescData []byte
)

func file_fight_message_proto_rawDescGZIP() []byte {
	file_fight_message_proto_rawDescOnce.Do(func() {
		file_fight_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fight_message_proto_rawDesc), len(file_fight_message_proto_rawDesc)))
	})
	return file_fight_message_proto_rawDescData
}

var file_fight_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fight_message_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_fight_message_proto_goTypes = []any{
	(Switch_Phase_Option)(0),    // 0: proto.Switch_Phase_Option
	(FightLogType)(0),           // 1: proto.FightLogType
	(*Buff)(nil),                // 2: proto.Buff
	(*CharacterStatus)(nil),     // 3: proto.CharacterStatus
	(*Tool)(nil),                // 4: proto.Tool
	(*Skill)(nil),               // 5: proto.Skill
	(*Site)(nil),                // 6: proto.Site
	(*FightStatus)(nil),         // 7: proto.FightStatus
	(*C2S_ChoseSkills)(nil),     // 8: proto.C2S_ChoseSkills
	(*C2S_UseTool)(nil),         // 9: proto.C2S_UseTool
	(*C2S_SwitchPhase)(nil),     // 10: proto.C2S_SwitchPhase
	(*Msg_SyncFightStatus)(nil), // 11: proto.Msg_SyncFightStatus
	(*AttackLog)(nil),           // 12: proto.AttackLog
	(*RecoverLog)(nil),          // 13: proto.RecoverLog
	(*CounterLog)(nil),          // 14: proto.CounterLog
	(*BuffLog)(nil),             // 15: proto.BuffLog
	(*DeathLog)(nil),            // 16: proto.DeathLog
	(*OtherLog)(nil),            // 17: proto.OtherLog
	(*FightLog)(nil),            // 18: proto.FightLog
	(*S2C_FightLogs)(nil),       // 19: proto.S2C_FightLogs
	(*FightMessage)(nil),        // 20: proto.FightMessage
	nil,                         // 21: proto.FightStatus.CountersEntry
}
var file_fight_message_proto_depIdxs = []int32{
	2,  // 0: proto.CharacterStatus.buffs:type_name -> proto.Buff
	3,  // 1: proto.FightStatus.characters:type_name -> proto.CharacterStatus
	6,  // 2: proto.FightStatus.sites:type_name -> proto.Site
	4,  // 3: proto.FightStatus.tools:type_name -> proto.Tool
	21, // 4: proto.FightStatus.counters:type_name -> proto.FightStatus.CountersEntry
	5,  // 5: proto.C2S_ChoseSkills.skills:type_name -> proto.Skill
	0,  // 6: proto.C2S_SwitchPhase.phase:type_name -> proto.Switch_Phase_Option
	7,  // 7: proto.Msg_SyncFightStatus.status:type_name -> proto.FightStatus
	1,  // 8: proto.FightLog.type:type_name -> proto.FightLogType
	12, // 9: proto.FightLog.attack:type_name -> proto.AttackLog
	13, // 10: proto.FightLog.recover:type_name -> proto.RecoverLog
	14, // 11: proto.FightLog.counter:type_name -> proto.CounterLog
	15, // 12: proto.FightLog.buff:type_name -> proto.BuffLog
	16, // 13: proto.FightLog.death:type_name -> proto.DeathLog
	17, // 14: proto.FightLog.other:type_name -> proto.OtherLog
	18, // 15: proto.S2C_FightLogs.logs:type_name -> proto.FightLog
	8,  // 16: proto.FightMessage.chose_skill:type_name -> proto.C2S_ChoseSkills
	9,  // 17: proto.FightMessage.use_tool:type_name -> proto.C2S_UseTool
	10, // 18: proto.FightMessage.switch_phase:type_name -> proto.C2S_SwitchPhase
	11, // 19: proto.FightMessage.sync_fight_status:type_name -> proto.Msg_SyncFightStatus
	19, // 20: proto.FightMessage.fight_logs:type_name -> proto.S2C_FightLogs
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_fight_message_proto_init() }
func file_fight_message_proto_init() {
	if File_fight_message_proto != nil {
		return
	}
	file_fight_message_proto_msgTypes[16].OneofWrappers = []any{
		(*FightLog_Attack)(nil),
		(*FightLog_Recover)(nil),
		(*FightLog_Counter)(nil),
		(*FightLog_Buff)(nil),
		(*FightLog_Death)(nil),
		(*FightLog_Other)(nil),
	}
	file_fight_message_proto_msgTypes[18].OneofWrappers = []any{
		(*FightMessage_ChoseSkill)(nil),
		(*FightMessage_UseTool)(nil),
		(*FightMessage_SwitchPhase)(nil),
		(*FightMessage_SyncFightStatus)(nil),
		(*FightMessage_FightLogs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fight_message_proto_rawDesc), len(file_fight_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fight_message_proto_goTypes,
		DependencyIndexes: file_fight_message_proto_depIdxs,
		EnumInfos:         file_fight_message_proto_enumTypes,
		MessageInfos:      file_fight_message_proto_msgTypes,
	}.Build()
	File_fight_message_proto = out.File
	file_fight_message_proto_goTypes = nil
	file_fight_message_proto_depIdxs = nil
}
