// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0--rc2
// source: fight_message.proto

package pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Switch_Phase_Option int32

const (
	Switch_Phase_Option_START_PHASE       Switch_Phase_Option = 0 // 开始本轮回合战斗
	Switch_Phase_Option_EXIT_FIGHT        Switch_Phase_Option = 1 // 退出战斗
	Switch_Phase_Option_RETURN_PREV_PHASE Switch_Phase_Option = 2 // 回到上一回合
)

// Enum value maps for Switch_Phase_Option.
var (
	Switch_Phase_Option_name = map[int32]string{
		0: "START_PHASE",
		1: "EXIT_FIGHT",
		2: "RETURN_PREV_PHASE",
	}
	Switch_Phase_Option_value = map[string]int32{
		"START_PHASE":       0,
		"EXIT_FIGHT":        1,
		"RETURN_PREV_PHASE": 2,
	}
)

func (x Switch_Phase_Option) Enum() *Switch_Phase_Option {
	p := new(Switch_Phase_Option)
	*p = x
	return p
}

func (x Switch_Phase_Option) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Switch_Phase_Option) Descriptor() protoreflect.EnumDescriptor {
	return file_fight_message_proto_enumTypes[0].Descriptor()
}

func (Switch_Phase_Option) Type() protoreflect.EnumType {
	return &file_fight_message_proto_enumTypes[0]
}

func (x Switch_Phase_Option) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Switch_Phase_Option.Descriptor instead.
func (Switch_Phase_Option) EnumDescriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{0}
}

type Buff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuffId        int32                  `protobuf:"varint,1,opt,name=buff_id,json=buffId,proto3" json:"buff_id,omitempty"` // buffID
	Time          int32                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`                   // buff持续时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buff) Reset() {
	*x = Buff{}
	mi := &file_fight_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buff) ProtoMessage() {}

func (x *Buff) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buff.ProtoReflect.Descriptor instead.
func (*Buff) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{0}
}

func (x *Buff) GetBuffId() int32 {
	if x != nil {
		return x.BuffId
	}
	return 0
}

func (x *Buff) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 角色状态
type CharacterStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        int32                  `protobuf:"varint,1,opt,name=health,proto3" json:"health,omitempty"`                                      // 生命值
	Attack        float64                `protobuf:"fixed64,2,opt,name=attack,proto3" json:"attack,omitempty"`                                     // 攻击倍率
	Defense       int32                  `protobuf:"varint,3,opt,name=defense,proto3" json:"defense,omitempty"`                                    // 防御值
	Buffs         []*Buff                `protobuf:"bytes,4,rep,name=buffs,proto3" json:"buffs,omitempty"`                                         // buff列表
	IsMyCharacter bool                   `protobuf:"varint,5,opt,name=is_my_character,json=isMyCharacter,proto3" json:"is_my_character,omitempty"` // 是否是我的角色
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterStatus) Reset() {
	*x = CharacterStatus{}
	mi := &file_fight_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStatus) ProtoMessage() {}

func (x *CharacterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStatus.ProtoReflect.Descriptor instead.
func (*CharacterStatus) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterStatus) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *CharacterStatus) GetAttack() float64 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *CharacterStatus) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *CharacterStatus) GetBuffs() []*Buff {
	if x != nil {
		return x.Buffs
	}
	return nil
}

func (x *CharacterStatus) GetIsMyCharacter() bool {
	if x != nil {
		return x.IsMyCharacter
	}
	return false
}

// 道具
type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        int32                  `protobuf:"varint,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"` // 道具ID
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 道具数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_fight_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{2}
}

func (x *Tool) GetToolId() int32 {
	if x != nil {
		return x.ToolId
	}
	return 0
}

func (x *Tool) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 技能
type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int32                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`             // 技能ID
	TargetId      int32                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`          // 目标ID
	CharacterId   int32                  `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // 角色ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_fight_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{3}
}

func (x *Skill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *Skill) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Skill) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

// 位置
type Site struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IsMainActionCharacter bool                   `protobuf:"varint,1,opt,name=is_main_action_character,json=isMainActionCharacter,proto3" json:"is_main_action_character,omitempty"` // 是否是行动角色
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_fight_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{4}
}

func (x *Site) GetIsMainActionCharacter() bool {
	if x != nil {
		return x.IsMainActionCharacter
	}
	return false
}

// 战斗状态
type FightStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsSelfRound    bool                   `protobuf:"varint,1,opt,name=is_self_round,json=isSelfRound,proto3" json:"is_self_round,omitempty"`                                                 // 是否是我的回合
	Round          int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                                                                                  // 回合数
	Characters     []*CharacterStatus     `protobuf:"bytes,3,rep,name=characters,proto3" json:"characters,omitempty"`                                                                         // 角色状态
	Sites          []*Site                `protobuf:"bytes,4,rep,name=sites,proto3" json:"sites,omitempty"`                                                                                   // 位置
	Tools          []*Tool                `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`                                                                                   // 道具列表
	NowFightStatus int32                  `protobuf:"varint,6,opt,name=now_fight_status,json=nowFightStatus,proto3" json:"now_fight_status,omitempty"`                                        // 当前战斗状态
	Counters       map[string]float32     `protobuf:"bytes,7,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // 计数器
	StateNumber    int32                  `protobuf:"varint,8,opt,name=state_number,json=stateNumber,proto3" json:"state_number,omitempty"`                                                   // 状态编号
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FightStatus) Reset() {
	*x = FightStatus{}
	mi := &file_fight_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FightStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FightStatus) ProtoMessage() {}

func (x *FightStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FightStatus.ProtoReflect.Descriptor instead.
func (*FightStatus) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{5}
}

func (x *FightStatus) GetIsSelfRound() bool {
	if x != nil {
		return x.IsSelfRound
	}
	return false
}

func (x *FightStatus) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *FightStatus) GetCharacters() []*CharacterStatus {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *FightStatus) GetSites() []*Site {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *FightStatus) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *FightStatus) GetNowFightStatus() int32 {
	if x != nil {
		return x.NowFightStatus
	}
	return 0
}

func (x *FightStatus) GetCounters() map[string]float32 {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *FightStatus) GetStateNumber() int32 {
	if x != nil {
		return x.StateNumber
	}
	return 0
}

// 选择技能
type C2S_ChoseSkills struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"` // 技能列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_ChoseSkills) Reset() {
	*x = C2S_ChoseSkills{}
	mi := &file_fight_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_ChoseSkills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ChoseSkills) ProtoMessage() {}

func (x *C2S_ChoseSkills) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ChoseSkills.ProtoReflect.Descriptor instead.
func (*C2S_ChoseSkills) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_ChoseSkills) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

// 使用道具
type C2S_UseTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        int32                  `protobuf:"varint,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`       // 道具ID
	TargetId      int32                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_UseTool) Reset() {
	*x = C2S_UseTool{}
	mi := &file_fight_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_UseTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_UseTool) ProtoMessage() {}

func (x *C2S_UseTool) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_UseTool.ProtoReflect.Descriptor instead.
func (*C2S_UseTool) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{7}
}

func (x *C2S_UseTool) GetToolId() int32 {
	if x != nil {
		return x.ToolId
	}
	return 0
}

func (x *C2S_UseTool) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 阶段切换
type C2S_SwitchPhase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         Switch_Phase_Option    `protobuf:"varint,1,opt,name=phase,proto3,enum=proto.Switch_Phase_Option" json:"phase,omitempty"` // 阶段选项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_SwitchPhase) Reset() {
	*x = C2S_SwitchPhase{}
	mi := &file_fight_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_SwitchPhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SwitchPhase) ProtoMessage() {}

func (x *C2S_SwitchPhase) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SwitchPhase.ProtoReflect.Descriptor instead.
func (*C2S_SwitchPhase) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{8}
}

func (x *C2S_SwitchPhase) GetPhase() Switch_Phase_Option {
	if x != nil {
		return x.Phase
	}
	return Switch_Phase_Option_START_PHASE
}

// 同步战斗状态请求
type Msg_SyncFightStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *FightStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`        // 战斗状态
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 消息发送时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg_SyncFightStatus) Reset() {
	*x = Msg_SyncFightStatus{}
	mi := &file_fight_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg_SyncFightStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg_SyncFightStatus) ProtoMessage() {}

func (x *Msg_SyncFightStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg_SyncFightStatus.ProtoReflect.Descriptor instead.
func (*Msg_SyncFightStatus) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{9}
}

func (x *Msg_SyncFightStatus) GetStatus() *FightStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Msg_SyncFightStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 顶层消息包装器 (Envelope)
type FightMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SequenceId uint64                 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"` // 消息序号 (用于处理乱序、丢包或消息确认)
	Timestamp  int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // 消息发送时间戳
	// Types that are valid to be assigned to Payload:
	//
	//	*FightMessage_ChoseSkill
	//	*FightMessage_UseTool
	//	*FightMessage_SwitchPhase
	//	*FightMessage_SyncFightStatus
	Payload       isFightMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FightMessage) Reset() {
	*x = FightMessage{}
	mi := &file_fight_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FightMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FightMessage) ProtoMessage() {}

func (x *FightMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fight_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FightMessage.ProtoReflect.Descriptor instead.
func (*FightMessage) Descriptor() ([]byte, []int) {
	return file_fight_message_proto_rawDescGZIP(), []int{10}
}

func (x *FightMessage) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *FightMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FightMessage) GetPayload() isFightMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FightMessage) GetChoseSkill() *C2S_ChoseSkills {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_ChoseSkill); ok {
			return x.ChoseSkill
		}
	}
	return nil
}

func (x *FightMessage) GetUseTool() *C2S_UseTool {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_UseTool); ok {
			return x.UseTool
		}
	}
	return nil
}

func (x *FightMessage) GetSwitchPhase() *C2S_SwitchPhase {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_SwitchPhase); ok {
			return x.SwitchPhase
		}
	}
	return nil
}

func (x *FightMessage) GetSyncFightStatus() *Msg_SyncFightStatus {
	if x != nil {
		if x, ok := x.Payload.(*FightMessage_SyncFightStatus); ok {
			return x.SyncFightStatus
		}
	}
	return nil
}

type isFightMessage_Payload interface {
	isFightMessage_Payload()
}

type FightMessage_ChoseSkill struct {
	ChoseSkill *C2S_ChoseSkills `protobuf:"bytes,3,opt,name=chose_skill,json=choseSkill,proto3,oneof"` // 选择技能
}

type FightMessage_UseTool struct {
	UseTool *C2S_UseTool `protobuf:"bytes,4,opt,name=use_tool,json=useTool,proto3,oneof"` // 使用道具
}

type FightMessage_SwitchPhase struct {
	SwitchPhase *C2S_SwitchPhase `protobuf:"bytes,5,opt,name=switch_phase,json=switchPhase,proto3,oneof"` // 阶段切换
}

type FightMessage_SyncFightStatus struct {
	SyncFightStatus *Msg_SyncFightStatus `protobuf:"bytes,6,opt,name=sync_fight_status,json=syncFightStatus,proto3,oneof"` // 同步战斗状态请求
}

func (*FightMessage_ChoseSkill) isFightMessage_Payload() {}

func (*FightMessage_UseTool) isFightMessage_Payload() {}

func (*FightMessage_SwitchPhase) isFightMessage_Payload() {}

func (*FightMessage_SyncFightStatus) isFightMessage_Payload() {}

var File_fight_message_proto protoreflect.FileDescriptor

const file_fight_message_proto_rawDesc = "" +
	"\n" +
	"\x13fight_message.proto\x12\x05proto\"3\n" +
	"\x04Buff\x12\x17\n" +
	"\abuff_id\x18\x01 \x01(\x05R\x06buffId\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x05R\x04time\"\xa6\x01\n" +
	"\x0fCharacterStatus\x12\x16\n" +
	"\x06health\x18\x01 \x01(\x05R\x06health\x12\x16\n" +
	"\x06attack\x18\x02 \x01(\x01R\x06attack\x12\x18\n" +
	"\adefense\x18\x03 \x01(\x05R\adefense\x12!\n" +
	"\x05buffs\x18\x04 \x03(\v2\v.proto.BuffR\x05buffs\x12&\n" +
	"\x0fis_my_character\x18\x05 \x01(\bR\risMyCharacter\"5\n" +
	"\x04Tool\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\x05R\x06toolId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"b\n" +
	"\x05Skill\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x05R\askillId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x05R\btargetId\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x05R\vcharacterId\"?\n" +
	"\x04Site\x127\n" +
	"\x18is_main_action_character\x18\x01 \x01(\bR\x15isMainActionCharacter\"\x8d\x03\n" +
	"\vFightStatus\x12\"\n" +
	"\ris_self_round\x18\x01 \x01(\bR\visSelfRound\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x126\n" +
	"\n" +
	"characters\x18\x03 \x03(\v2\x16.proto.CharacterStatusR\n" +
	"characters\x12!\n" +
	"\x05sites\x18\x04 \x03(\v2\v.proto.SiteR\x05sites\x12!\n" +
	"\x05tools\x18\x05 \x03(\v2\v.proto.ToolR\x05tools\x12(\n" +
	"\x10now_fight_status\x18\x06 \x01(\x05R\x0enowFightStatus\x12<\n" +
	"\bcounters\x18\a \x03(\v2 .proto.FightStatus.CountersEntryR\bcounters\x12!\n" +
	"\fstate_number\x18\b \x01(\x05R\vstateNumber\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"7\n" +
	"\x0fC2S_ChoseSkills\x12$\n" +
	"\x06skills\x18\x01 \x03(\v2\f.proto.SkillR\x06skills\"C\n" +
	"\vC2S_UseTool\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\x05R\x06toolId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x05R\btargetId\"C\n" +
	"\x0fC2S_SwitchPhase\x120\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1a.proto.Switch_Phase_OptionR\x05phase\"_\n" +
	"\x13Msg_SyncFightStatus\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.proto.FightStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xcb\x02\n" +
	"\fFightMessage\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\x04R\n" +
	"sequenceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x129\n" +
	"\vchose_skill\x18\x03 \x01(\v2\x16.proto.C2S_ChoseSkillsH\x00R\n" +
	"choseSkill\x12/\n" +
	"\buse_tool\x18\x04 \x01(\v2\x12.proto.C2S_UseToolH\x00R\auseTool\x12;\n" +
	"\fswitch_phase\x18\x05 \x01(\v2\x16.proto.C2S_SwitchPhaseH\x00R\vswitchPhase\x12H\n" +
	"\x11sync_fight_status\x18\x06 \x01(\v2\x1a.proto.Msg_SyncFightStatusH\x00R\x0fsyncFightStatusB\t\n" +
	"\apayload*M\n" +
	"\x13Switch_Phase_Option\x12\x0f\n" +
	"\vSTART_PHASE\x10\x00\x12\x0e\n" +
	"\n" +
	"EXIT_FIGHT\x10\x01\x12\x15\n" +
	"\x11RETURN_PREV_PHASE\x10\x02B\x06Z\x04./pdb\x06proto3"

var (
	file_fight_message_proto_rawDescOnce sync.Once
	file_fight_message_proto_rawDescData []byte
)

func file_fight_message_proto_rawDescGZIP() []byte {
	file_fight_message_proto_rawDescOnce.Do(func() {
		file_fight_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fight_message_proto_rawDesc), len(file_fight_message_proto_rawDesc)))
	})
	return file_fight_message_proto_rawDescData
}

var file_fight_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fight_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_fight_message_proto_goTypes = []any{
	(Switch_Phase_Option)(0),    // 0: proto.Switch_Phase_Option
	(*Buff)(nil),                // 1: proto.Buff
	(*CharacterStatus)(nil),     // 2: proto.CharacterStatus
	(*Tool)(nil),                // 3: proto.Tool
	(*Skill)(nil),               // 4: proto.Skill
	(*Site)(nil),                // 5: proto.Site
	(*FightStatus)(nil),         // 6: proto.FightStatus
	(*C2S_ChoseSkills)(nil),     // 7: proto.C2S_ChoseSkills
	(*C2S_UseTool)(nil),         // 8: proto.C2S_UseTool
	(*C2S_SwitchPhase)(nil),     // 9: proto.C2S_SwitchPhase
	(*Msg_SyncFightStatus)(nil), // 10: proto.Msg_SyncFightStatus
	(*FightMessage)(nil),        // 11: proto.FightMessage
	nil,                         // 12: proto.FightStatus.CountersEntry
}
var file_fight_message_proto_depIdxs = []int32{
	1,  // 0: proto.CharacterStatus.buffs:type_name -> proto.Buff
	2,  // 1: proto.FightStatus.characters:type_name -> proto.CharacterStatus
	5,  // 2: proto.FightStatus.sites:type_name -> proto.Site
	3,  // 3: proto.FightStatus.tools:type_name -> proto.Tool
	12, // 4: proto.FightStatus.counters:type_name -> proto.FightStatus.CountersEntry
	4,  // 5: proto.C2S_ChoseSkills.skills:type_name -> proto.Skill
	0,  // 6: proto.C2S_SwitchPhase.phase:type_name -> proto.Switch_Phase_Option
	6,  // 7: proto.Msg_SyncFightStatus.status:type_name -> proto.FightStatus
	7,  // 8: proto.FightMessage.chose_skill:type_name -> proto.C2S_ChoseSkills
	8,  // 9: proto.FightMessage.use_tool:type_name -> proto.C2S_UseTool
	9,  // 10: proto.FightMessage.switch_phase:type_name -> proto.C2S_SwitchPhase
	10, // 11: proto.FightMessage.sync_fight_status:type_name -> proto.Msg_SyncFightStatus
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_fight_message_proto_init() }
func file_fight_message_proto_init() {
	if File_fight_message_proto != nil {
		return
	}
	file_fight_message_proto_msgTypes[10].OneofWrappers = []any{
		(*FightMessage_ChoseSkill)(nil),
		(*FightMessage_UseTool)(nil),
		(*FightMessage_SwitchPhase)(nil),
		(*FightMessage_SyncFightStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fight_message_proto_rawDesc), len(file_fight_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fight_message_proto_goTypes,
		DependencyIndexes: file_fight_message_proto_depIdxs,
		EnumInfos:         file_fight_message_proto_enumTypes,
		MessageInfos:      file_fight_message_proto_msgTypes,
	}.Build()
	File_fight_message_proto = out.File
	file_fight_message_proto_goTypes = nil
	file_fight_message_proto_depIdxs = nil
}
