// global_message.proto
// 非战斗（大世界）全局消息协议：走动、剧情进度同步、状态下推等。
// 与战斗协议（fight_message.proto）并列：信封同样是双向的 GlobalMessage，
// 客户端上行 move / story_progress，服务端下行 sync_state / ack。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0--rc2
// source: global_message.proto

package pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 大世界 2D 坐标
type WorldPos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapName       string                 `protobuf:"bytes,1,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"` // 地图标识（如 "town"、"wild"）
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`                           // x 坐标
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`                           // y 坐标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldPos) Reset() {
	*x = WorldPos{}
	mi := &file_global_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldPos) ProtoMessage() {}

func (x *WorldPos) ProtoReflect() protoreflect.Message {
	mi := &file_global_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldPos.ProtoReflect.Descriptor instead.
func (*WorldPos) Descriptor() ([]byte, []int) {
	return file_global_message_proto_rawDescGZIP(), []int{0}
}

func (x *WorldPos) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *WorldPos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WorldPos) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 剧情进度（单人单档；游标地址见 docs/story-json-schema.md）
type StoryProgressData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Main          string                 `protobuf:"bytes,1,opt,name=main,proto3" json:"main,omitempty"`                                                                                   // 主线游标；"" = 主线未开始/已重置
	Branches      map[string]string      `protobuf:"bytes,2,rep,name=branches,proto3" json:"branches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 支线：key = 支线前缀（如 "0.1"），值 "" = 该支线未开始
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryProgressData) Reset() {
	*x = StoryProgressData{}
	mi := &file_global_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryProgressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryProgressData) ProtoMessage() {}

func (x *StoryProgressData) ProtoReflect() protoreflect.Message {
	mi := &file_global_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryProgressData.ProtoReflect.Descriptor instead.
func (*StoryProgressData) Descriptor() ([]byte, []int) {
	return file_global_message_proto_rawDescGZIP(), []int{1}
}

func (x *StoryProgressData) GetMain() string {
	if x != nil {
		return x.Main
	}
	return ""
}

func (x *StoryProgressData) GetBranches() map[string]string {
	if x != nil {
		return x.Branches
	}
	return nil
}

// C2S：大世界走动（客户端上报新位置）
type C2S_Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *WorldPos              `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_Move) Reset() {
	*x = C2S_Move{}
	mi := &file_global_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Move) ProtoMessage() {}

func (x *C2S_Move) ProtoReflect() protoreflect.Message {
	mi := &file_global_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Move.ProtoReflect.Descriptor instead.
func (*C2S_Move) Descriptor() ([]byte, []int) {
	return file_global_message_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_Move) GetPos() *WorldPos {
	if x != nil {
		return x.Pos
	}
	return nil
}

// C2S：同步剧情进度
type C2S_StoryProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *StoryProgressData     `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_StoryProgress) Reset() {
	*x = C2S_StoryProgress{}
	mi := &file_global_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_StoryProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_StoryProgress) ProtoMessage() {}

func (x *C2S_StoryProgress) ProtoReflect() protoreflect.Message {
	mi := &file_global_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_StoryProgress.ProtoReflect.Descriptor instead.
func (*C2S_StoryProgress) Descriptor() ([]byte, []int) {
	return file_global_message_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_StoryProgress) GetProgress() *StoryProgressData {
	if x != nil {
		return x.Progress
	}
	return nil
}

// C2S：请求服务端下发一次 SyncState（备用；默认连接即推）
type C2S_SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_SyncRequest) Reset() {
	*x = C2S_SyncRequest{}
	mi := &file_global_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SyncRequest) ProtoMessage() {}

func (x *C2S_SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_global_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SyncRequest.ProtoReflect.Descriptor instead.
func (*C2S_SyncRequest) Descriptor() ([]byte, []int) {
	return file_global_message_proto_rawDescGZIP(), []int{4}
}

// S2C：玩家全局状态快照（连接建立后先推一次）
type S2C_SyncState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doing         int32                  `protobuf:"varint,1,opt,name=doing,proto3" json:"doing,omitempty"`                                                                                                // 正在做的事（0 剧情 / 1 战斗 / 2 无事 / 3 移动）
	DoingMap      map[string]string      `protobuf:"bytes,2,rep,name=doing_map,json=doingMap,proto3" json:"doing_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 正在做的事的详情（如移动坐标）
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int32                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Location      *WorldPos              `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"` // 玩家当前位置
	Story         *StoryProgressData     `protobuf:"bytes,6,opt,name=story,proto3" json:"story,omitempty"`       // 剧情进度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_SyncState) Reset() {
	*x = S2C_SyncState{}
	mi := &file_global_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_SyncState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SyncState) ProtoMessage() {}

func (x *S2C_SyncState) ProtoReflect() protoreflect.Message {
	mi := &file_global_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SyncState.ProtoReflect.Descriptor instead.
func (*S2C_SyncState) Descriptor() ([]byte, []int) {
	return file_global_message_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_SyncState) GetDoing() int32 {
	if x != nil {
		return x.Doing
	}
	return 0
}

func (x *S2C_SyncState) GetDoingMap() map[string]string {
	if x != nil {
		return x.DoingMap
	}
	return nil
}

func (x *S2C_SyncState) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *S2C_SyncState) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *S2C_SyncState) GetLocation() *WorldPos {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *S2C_SyncState) GetStory() *StoryProgressData {
	if x != nil {
		return x.Story
	}
	return nil
}

// S2C：通用回执
type S2C_Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` // 0 = 成功；非 0 = 错误码（暂未细分）
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_Ack) Reset() {
	*x = S2C_Ack{}
	mi := &file_global_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Ack) ProtoMessage() {}

func (x *S2C_Ack) ProtoReflect() protoreflect.Message {
	mi := &file_global_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Ack.ProtoReflect.Descriptor instead.
func (*S2C_Ack) Descriptor() ([]byte, []int) {
	return file_global_message_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *S2C_Ack) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S2C_Ack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 顶层消息包装器（Envelope，双向）
type GlobalMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SequenceId uint64                 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"` // 消息序号
	Timestamp  int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // 消息发送时间戳
	// Types that are valid to be assigned to Payload:
	//
	//	*GlobalMessage_Move
	//	*GlobalMessage_StoryProgress
	//	*GlobalMessage_SyncRequest
	//	*GlobalMessage_SyncState
	//	*GlobalMessage_Ack
	Payload       isGlobalMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalMessage) Reset() {
	*x = GlobalMessage{}
	mi := &file_global_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalMessage) ProtoMessage() {}

func (x *GlobalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_global_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalMessage.ProtoReflect.Descriptor instead.
func (*GlobalMessage) Descriptor() ([]byte, []int) {
	return file_global_message_proto_rawDescGZIP(), []int{7}
}

func (x *GlobalMessage) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *GlobalMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GlobalMessage) GetPayload() isGlobalMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GlobalMessage) GetMove() *C2S_Move {
	if x != nil {
		if x, ok := x.Payload.(*GlobalMessage_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GlobalMessage) GetStoryProgress() *C2S_StoryProgress {
	if x != nil {
		if x, ok := x.Payload.(*GlobalMessage_StoryProgress); ok {
			return x.StoryProgress
		}
	}
	return nil
}

func (x *GlobalMessage) GetSyncRequest() *C2S_SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*GlobalMessage_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *GlobalMessage) GetSyncState() *S2C_SyncState {
	if x != nil {
		if x, ok := x.Payload.(*GlobalMessage_SyncState); ok {
			return x.SyncState
		}
	}
	return nil
}

func (x *GlobalMessage) GetAck() *S2C_Ack {
	if x != nil {
		if x, ok := x.Payload.(*GlobalMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isGlobalMessage_Payload interface {
	isGlobalMessage_Payload()
}

type GlobalMessage_Move struct {
	Move *C2S_Move `protobuf:"bytes,3,opt,name=move,proto3,oneof"` // 客户端：走动
}

type GlobalMessage_StoryProgress struct {
	StoryProgress *C2S_StoryProgress `protobuf:"bytes,4,opt,name=story_progress,json=storyProgress,proto3,oneof"` // 客户端：剧情进度
}

type GlobalMessage_SyncRequest struct {
	SyncRequest *C2S_SyncRequest `protobuf:"bytes,5,opt,name=sync_request,json=syncRequest,proto3,oneof"` // 客户端：请求同步
}

type GlobalMessage_SyncState struct {
	SyncState *S2C_SyncState `protobuf:"bytes,6,opt,name=sync_state,json=syncState,proto3,oneof"` // 服务端：状态快照
}

type GlobalMessage_Ack struct {
	Ack *S2C_Ack `protobuf:"bytes,7,opt,name=ack,proto3,oneof"` // 服务端：回执
}

func (*GlobalMessage_Move) isGlobalMessage_Payload() {}

func (*GlobalMessage_StoryProgress) isGlobalMessage_Payload() {}

func (*GlobalMessage_SyncRequest) isGlobalMessage_Payload() {}

func (*GlobalMessage_SyncState) isGlobalMessage_Payload() {}

func (*GlobalMessage_Ack) isGlobalMessage_Payload() {}

var File_global_message_proto protoreflect.FileDescriptor

const file_global_message_proto_rawDesc = "" +
	"\n" +
	"\x14global_message.proto\x12\x05proto\"A\n" +
	"\bWorldPos\x12\x19\n" +
	"\bmap_name\x18\x01 \x01(\tR\amapName\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\xa8\x01\n" +
	"\x11StoryProgressData\x12\x12\n" +
	"\x04main\x18\x01 \x01(\tR\x04main\x12B\n" +
	"\bbranches\x18\x02 \x03(\v2&.proto.StoryProgressData.BranchesEntryR\bbranches\x1a;\n" +
	"\rBranchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\bC2S_Move\x12!\n" +
	"\x03pos\x18\x01 \x01(\v2\x0f.proto.WorldPosR\x03pos\"I\n" +
	"\x11C2S_StoryProgress\x124\n" +
	"\bprogress\x18\x01 \x01(\v2\x18.proto.StoryProgressDataR\bprogress\"\x11\n" +
	"\x0fC2S_SyncRequest\"\xa8\x02\n" +
	"\rS2C_SyncState\x12\x14\n" +
	"\x05doing\x18\x01 \x01(\x05R\x05doing\x12?\n" +
	"\tdoing_map\x18\x02 \x03(\v2\".proto.S2C_SyncState.DoingMapEntryR\bdoingMap\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x05R\x03exp\x12+\n" +
	"\blocation\x18\x05 \x01(\v2\x0f.proto.WorldPosR\blocation\x12.\n" +
	"\x05story\x18\x06 \x01(\v2\x18.proto.StoryProgressDataR\x05story\x1a;\n" +
	"\rDoingMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\aS2C_Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xdb\x02\n" +
	"\rGlobalMessage\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\x04R\n" +
	"sequenceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x04move\x18\x03 \x01(\v2\x0f.proto.C2S_MoveH\x00R\x04move\x12A\n" +
	"\x0estory_progress\x18\x04 \x01(\v2\x18.proto.C2S_StoryProgressH\x00R\rstoryProgress\x12;\n" +
	"\fsync_request\x18\x05 \x01(\v2\x16.proto.C2S_SyncRequestH\x00R\vsyncRequest\x125\n" +
	"\n" +
	"sync_state\x18\x06 \x01(\v2\x14.proto.S2C_SyncStateH\x00R\tsyncState\x12\"\n" +
	"\x03ack\x18\a \x01(\v2\x0e.proto.S2C_AckH\x00R\x03ackB\t\n" +
	"\apayloadB\x06Z\x04./pdb\x06proto3"

var (
	file_global_message_proto_rawDescOnce sync.Once
	file_global_message_proto_rawDescData []byte
)

func file_global_message_proto_rawDescGZIP() []byte {
	file_global_message_proto_rawDescOnce.Do(func() {
		file_global_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_global_message_proto_rawDesc), len(file_global_message_proto_rawDesc)))
	})
	return file_global_message_proto_rawDescData
}

var file_global_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_global_message_proto_goTypes = []any{
	(*WorldPos)(nil),          // 0: proto.WorldPos
	(*StoryProgressData)(nil), // 1: proto.StoryProgressData
	(*C2S_Move)(nil),          // 2: proto.C2S_Move
	(*C2S_StoryProgress)(nil), // 3: proto.C2S_StoryProgress
	(*C2S_SyncRequest)(nil),   // 4: proto.C2S_SyncRequest
	(*S2C_SyncState)(nil),     // 5: proto.S2C_SyncState
	(*S2C_Ack)(nil),           // 6: proto.S2C_Ack
	(*GlobalMessage)(nil),     // 7: proto.GlobalMessage
	nil,                       // 8: proto.StoryProgressData.BranchesEntry
	nil,                       // 9: proto.S2C_SyncState.DoingMapEntry
}
var file_global_message_proto_depIdxs = []int32{
	8,  // 0: proto.StoryProgressData.branches:type_name -> proto.StoryProgressData.BranchesEntry
	0,  // 1: proto.C2S_Move.pos:type_name -> proto.WorldPos
	1,  // 2: proto.C2S_StoryProgress.progress:type_name -> proto.StoryProgressData
	9,  // 3: proto.S2C_SyncState.doing_map:type_name -> proto.S2C_SyncState.DoingMapEntry
	0,  // 4: proto.S2C_SyncState.location:type_name -> proto.WorldPos
	1,  // 5: proto.S2C_SyncState.story:type_name -> proto.StoryProgressData
	2,  // 6: proto.GlobalMessage.move:type_name -> proto.C2S_Move
	3,  // 7: proto.GlobalMessage.story_progress:type_name -> proto.C2S_StoryProgress
	4,  // 8: proto.GlobalMessage.sync_request:type_name -> proto.C2S_SyncRequest
	5,  // 9: proto.GlobalMessage.sync_state:type_name -> proto.S2C_SyncState
	6,  // 10: proto.GlobalMessage.ack:type_name -> proto.S2C_Ack
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_global_message_proto_init() }
func file_global_message_proto_init() {
	if File_global_message_proto != nil {
		return
	}
	file_global_message_proto_msgTypes[7].OneofWrappers = []any{
		(*GlobalMessage_Move)(nil),
		(*GlobalMessage_StoryProgress)(nil),
		(*GlobalMessage_SyncRequest)(nil),
		(*GlobalMessage_SyncState)(nil),
		(*GlobalMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_global_message_proto_rawDesc), len(file_global_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_message_proto_goTypes,
		DependencyIndexes: file_global_message_proto_depIdxs,
		MessageInfos:      file_global_message_proto_msgTypes,
	}.Build()
	File_global_message_proto = out.File
	file_global_message_proto_goTypes = nil
	file_global_message_proto_depIdxs = nil
}
