// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "1473443474@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/login": {
            "post": {
                "description": "通过用户名密码进行登录，返回双令牌（access_token + refresh_token）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回双令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/logout": {
            "post": {
                "description": "退出登录接口（需要 access token 和 refresh token）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "用户退出登录接口",
                "parameters": [
                    {
                        "description": "退出登录请求参数（refresh_token）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RefreshReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "退出登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/refresh": {
            "post": {
                "description": "使用 refresh token 获取新的双令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RefreshReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回新的双令牌",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "注册新用户，返回双令牌（access_token + refresh_token）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回双令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v1/send_verify_code": {
            "get": {
                "description": "发送验证码到指定邮箱",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证模块"
                ],
                "summary": "发送验证码接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证目标（邮箱）",
                        "name": "verifier",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证类型（email）",
                        "name": "verifier_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "发送验证码成功",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v2/data": {
            "get": {
                "description": "获取用户数据，包括邮箱、状态等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户数据",
                "responses": {
                    "200": {
                        "description": "成功 data: 用户数据对象",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v2/ws-code": {
            "get": {
                "description": "获取 WebSocket 连接码，用于连接 WebSocket 服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取 WebSocket 连接码",
                "responses": {
                    "200": {
                        "description": "成功 data: {\"wsCode\": \"123456\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/config/emails": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-系统配置"
                ],
                "summary": "邮箱配置列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/config/emails/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-系统配置"
                ],
                "summary": "修改邮箱配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "邮箱配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "邮箱配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUpdateEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/characters": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-角色"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "角色信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminCreateCharacterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/characters/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-角色"
                ],
                "summary": "角色列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/characters/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-角色"
                ],
                "summary": "角色详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-角色"
                ],
                "summary": "修改角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUpdateCharacterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/enemies": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-敌人"
                ],
                "summary": "创建敌人",
                "parameters": [
                    {
                        "description": "敌人信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminCreateEnemyReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/enemies/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-敌人"
                ],
                "summary": "敌人列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/enemies/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-敌人"
                ],
                "summary": "敌人详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "敌人ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-敌人"
                ],
                "summary": "修改敌人",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "敌人ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "敌人信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUpdateEnemyReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/skills": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-技能"
                ],
                "summary": "创建技能",
                "parameters": [
                    {
                        "description": "技能信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminCreateSkillReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/skills/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-技能"
                ],
                "summary": "技能列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/skills/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-技能"
                ],
                "summary": "技能详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "技能ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-技能"
                ],
                "summary": "修改技能",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "技能ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "技能信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUpdateSkillReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/tools": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-道具"
                ],
                "summary": "创建道具",
                "parameters": [
                    {
                        "description": "道具信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminCreateToolReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/tools/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-道具"
                ],
                "summary": "道具列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/game/tools/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-道具"
                ],
                "summary": "道具详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "道具ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-游戏内容-道具"
                ],
                "summary": "修改道具",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "道具ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "道具信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUpdateToolReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/players/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-玩家管理"
                ],
                "summary": "玩家列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/players/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-玩家管理"
                ],
                "summary": "玩家详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "玩家ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/players/{id}/ban": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-玩家管理"
                ],
                "summary": "封禁玩家",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "玩家ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/players/{id}/exp": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-玩家管理"
                ],
                "summary": "修改玩家经验",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "玩家ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "经验值",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUpdatePlayerExpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/players/{id}/level": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-玩家管理"
                ],
                "summary": "修改玩家等级",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "玩家ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "等级",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUpdatePlayerLevelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/players/{id}/unban": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-玩家管理"
                ],
                "summary": "解封玩家",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "玩家ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/stats/items": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-数据统计"
                ],
                "summary": "道具分布",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/stats/online": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-数据统计"
                ],
                "summary": "在线统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/stats/overview": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-数据统计"
                ],
                "summary": "数据总览",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/users/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-用户管理"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/users/{id}/disable": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-用户管理"
                ],
                "summary": "禁用用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/users/{id}/enable": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-用户管理"
                ],
                "summary": "启用用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/api/v3/admin/users/{id}/role": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员-用户管理"
                ],
                "summary": "修改用户角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdminUpdateRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.AdminCreateCharacterReq": {
            "type": "object",
            "required": [
                "health",
                "name",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "health": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "owner_number": {
                    "type": "integer",
                    "minimum": 0
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "request.AdminCreateEnemyReq": {
            "type": "object",
            "required": [
                "health",
                "name",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "health": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "request.AdminCreateSkillReq": {
            "type": "object",
            "required": [
                "character_id",
                "name",
                "type"
            ],
            "properties": {
                "character_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "request.AdminCreateToolReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.AdminUpdateCharacterReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "health": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "owner_number": {
                    "type": "integer",
                    "minimum": 0
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "request.AdminUpdateEmailReq": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "max_count": {
                    "type": "integer"
                },
                "pass": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "request.AdminUpdateEnemyReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "health": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "request.AdminUpdatePlayerExpReq": {
            "type": "object",
            "required": [
                "exp"
            ],
            "properties": {
                "exp": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "request.AdminUpdatePlayerLevelReq": {
            "type": "object",
            "required": [
                "level"
            ],
            "properties": {
                "level": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "request.AdminUpdateRoleReq": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "user"
                    ]
                }
            }
        },
        "request.AdminUpdateSkillReq": {
            "type": "object",
            "properties": {
                "character_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "request.AdminUpdateToolReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.RefreshReq": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "request.RegisterReq": {
            "type": "object",
            "required": [
                "code",
                "email",
                "name",
                "password"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 6,
                    "minLength": 6
                },
                "email": {
                    "type": "string",
                    "maxLength": 50
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                }
            }
        },
        "response.LoginResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "response.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务码：0 成功，非 0 失败",
                    "type": "integer"
                },
                "data": {
                    "description": "业务数据"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "DisembodiedSpecter API",
	Description:      "DisembodiedSpecter API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
